@startuml
skinparam linetype ortho
hide empty members

    component "GeoVisEngine\n"{
    component GeoVisCoreVue
    component GeoVisCore 
     
    

    component Animation
    component Camera
    component GeoPosition
    component Utils
    component Visualization

    Camera - TrackballCamera

    Visualization ..> TrackballCamera : use
    Visualization --> GeoPosition
    Camera --> GeoPosition
    Camera --> Utils
    Camera --> Animation

    GeoVisCoreVue *--> GeoVisCore
    GeoVisCore *--> Camera
    }
@enduml