@startuml
actor Application
boundary GeoVisCore
participant "newVis:Visualization" as Visualization
participant "oldVis:Visualization" as VisualizationOld
control "cameraController\n:TrackballController" as TrackballController
control "renderer\n:THREE.Renderer" as Renderer
activate VisualizationOld
activate Application

create Visualization
Application -> Visualization : new
activate Visualization
Visualization -> Visualization : setupOwnMeta(meta)
alt vis has parents
    loop for each parent
        Visualization -> Visualization : parents.push(parent)
        Visualization -> Visualization : _setupMeta()
    end
end

activate TrackballController
activate GeoVisCore
activate Renderer
Application -> GeoVisCore : run(vis)
alt old vis exists
    GeoVisCore -> VisualizationOld : _destroy()
    loop for each vis.parents as parent
        VisualizationOld -> VisualizationOld : parent._destroy()
        activate VisualizationOld

        VisualizationOld -> VisualizationOld : destroy()
        deactivate VisualizationOld
        deactivate VisualizationOld
    end
end

note over GeoVisCore
    scene.dispose()
    scene = new THREE.Scene()
    group = new THREE.Group()
end note

GeoVisCore -> TrackballController : setGroup(group)

GeoVisCore -> Visualization : _setup(scene, group, cameraController)
activate Visualization

loop for each vis.parents as parent
    Visualization -> Visualization : parent._setup(\n\tscene, \n\tgroup, \n\tcameraController\n)
    activate Visualization

    Visualization -> Visualization : setupCamera(cameraController)
    Visualization -> Visualization : setupScene(scene, group)
end
deactivate Visualization

activate Visualization
GeoVisCore -> GeoVisCore : _run()
activate GeoVisCore

loop main loop triggered with requestAnimationFrame
    alt is destroy requested
        GeoVisCore -> GeoVisCore : this.destroyRequested = false
    else
        GeoVisCore -> GeoVisCore : requestAnimationFrame(()=>this._run())
    end

note over GeoVisCore
    TWEEN.update(TWEEN.now())
end note

GeoVisCore -> TrackballController : update(deltaFactor)
GeoVisCore -> Visualization : _update(deltaFactor)
loop for each vis.parents as parent
    Visualization -> Visualization : parent._update(deltaFactor)
    activate Visualization

    Visualization -> Visualization : update(cameraController)
end
deactivate Visualization
GeoVisCore -> Renderer : render(scene, camera)
end   
deactivate GeoVisCore
GeoVisCore -> Visualization : _destroy()
loop for each vis.parents as parent
    Visualization -> Visualization : parent._destroy()
    activate Visualization

    Visualization -> Visualization : destroy()
deactivate Visualization
deactivate Visualization
end
@enduml