@startuml
class GeoVisCoreVue
class Compass
class VizualizationInfo
class VizualizationControls
class CoreControls
hide empty members
GeoVisCoreVue --> CoreControls
CoreControls --> VizualizationInfo
CoreControls --> Compass
CoreControls --> VizualizationControls
@enduml