@startuml
scale 1
skinparam linetype ortho
hide empty members

    component "Application\n" as Application {
        component VisPicker
        component VisViewer
    }

    component "GeoVisEngine\n" as GVE{
    component GeoVisCoreVue
    component GeoVisCore 
     
    

    component Animation
    component Camera
    component GeoPosition
    component Utils
    component Visualization

    Camera - TrackballCamera

    Visualization ..> TrackballCamera : use
    Visualization --> GeoPosition
    Camera --> GeoPosition
    Camera --> Utils
    Camera --> Animation

    GeoVisCoreVue *--> GeoVisCore
    GeoVisCore *--> Camera
    }

    Application .down.> GVE 
@enduml